---
record_path: "owt"
device: "cuda"
train_data_path: "data/owt/owt_train.npy"
val_data_path: "data/owt/owt_valid.npy"
vocab_size: 32000
context_length: 256
num_layers: 4
d_model: 512
num_heads: 16
d_ff: 1344
model_eps: 1.0e-5
theta: 10000
learning_rate: 3.0e-4
betas: [0.9, 0.999]
opt_eps: 1.0e-8
weight_decay: 0.01
num_epochs: 100
batch_size: 32
num_total_processes: 327680000
log_step: 100
early_stop: 10
checkpoint_max_num: 20
max_norm: 5.0
grad_eps: 1.0e-6
lr_max: 3.0e-4
lr_min: 3.0e-5
warm_step: 1200
